[package]
org = "healthcare"
name = "health.fhir.r4.uscore501.careteam"
version = "1.0.0"
distribution = "2201.8.4"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "CareTeam", "r4", "health.fhir.r4.uscore501"]
template = true

[[dependency]]
org = "ballerinax"
name="health.fhir.r4"
version="4.3.4"


