[package]
org = "healthcare"
name = "health.fhir.r4.uscore501.patient"
version = "1.0.0"
distribution = "2201.8.5"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Patient", "r4", "health.fhir.r4.uscore501"]
template = true

[[dependency]]
org = "ballerinax"
name="health.fhir.r4"
version="5.1.0"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.international401"
version = "2.1.0"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.parser"
version = "5.1.0"